# Node.js React Web App to Linux on Azure
# Build a Node.js React app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'CICD'
    scriptLocation: inlineScript
    inlineScript: |
      ls -l
      mkdir repo
      cp -r build repo

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/repo'  
    includeRootFolder: false
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
      
- task: DownloadBuildArtifacts@0
  displayName: 'Download the build artifacts'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(build.artifactstagingdirectory)'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: 'CICD'
    appType: webAppLinux
    WebAppName: 'loram-webportal'
    packageForLinux: '$(build.artifactstagingdirectory)/drop/*.zip'
    RuntimeStack: 'NODE|14-lts'